name: Lint Code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: npm/action-setup@v2
        name: Install npm
        id: npm-install
        with:
          version: 8.6.10
          run_install: false

      - name: Get npm store directory
        id: npm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(npm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup npm cache
        with:
          path: ${{ steps.npm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-npm-store-${{ hashFiles('**/npm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-store-

      - name: Start Lint Code
        run: |
          npm install --no-frozen-lockfile
          npm lint
          npm typecheck
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
